#!/bin/sh

echo "Build pxdev Package..."
chmod +x ./pixtend/makelib
chmod +x ./PiXtend_V1/pxauto/makepxauto
chmod +x ./PiXtend_V1/pixtendtool/makepixtendtool
chmod +x ./PiXtend_V2/pxauto2s/makepxauto2s
chmod +x ./PiXtend_V2/pixtendtool2s/makepixtendtool2s

echo "Build pixtend Library..."
cd pixtend
./makelib go
cd ..
echo "Build pxauto..."
cd PiXtend_V1/pxauto
./makepxauto go
cd ..
echo "Build pixtendtool..."
cd pixtendtool
./makepixtendtool go
cd ..
cd ..
echo "Build pxauto2s..."
cd PiXtend_V2/pxauto2s
./makepxauto2s go
cd ..
echo "Build pixtendtool2s..."
cd pixtendtool2s
./makepixtendtool2s go
cd ..
cd ..
echo "done"
