#!/bin/sh

case $1 in
	go)
		echo "MAKELIBSCRIPT: start making library"
		sudo rm -rf pixtend.o
		echo "./pixtend.o deleted"
		sudo rm -rf libpixtend.a
		echo "./libpixtend.a deleted"
		sudo rm -rf /usr/local/lib/libpixtend.a
		echo "/usr/local/lib/libpixtend.a deleted"
		sudo rm -rf /usr/local/include/pixtend.h
		echo "/usr/local/include/pixtend.h deleted"
		echo "MAKELIBSCRIPT: deleted old files"
		sudo gcc -c pixtend.c
		echo "MAKELIBSCRIPT: pixtend.c compiled"
		sudo ar crs libpixtend.a pixtend.o
		echo "MAKELIBSCRIPT: created archive libpixtend.a"
		sudo ranlib libpixtend.a
		echo "MAKELIBSCRIPT: generated index for libpixtend.a"
		sudo cp -p libpixtend.a /usr/local/lib
		sudo cp -p pixtend.h /usr/local/include
		echo "MAKELIBSCRIPT: copied lib-files to /usr/local"
		echo "MAKELIBSCRIPT: DONE!!"
		;;
	clean)
		echo "MAKELIBSCRIPT: cleaning library files"
		sudo rm -rf pixtend.o
		echo "./pixtend.o deleted"
		sudo rm -rf libpixtend.a
		echo "./libpixtend.a deleted"
		sudo rm -rf /usr/local/lib/libpixtend.a
		echo "/usr/local/lib/libpixtend.a deleted"
		sudo rm -rf /usr/local/include/pixtend.h
		echo "/usr/local/include/pixtend.h deleted"
		echo "MAKELIBSCRIPT: DONE!!"
		;;
	*)
		echo "MAKELIBSCRIPT: Available Options are \"go\" and \"clean\""
		;;
esac
		
