#!/bin/sh

case $1 in
	go)
		echo "makepxauto2l: start making pxauto2l"
		sudo rm -rf pxauto2l.o
		echo "./pxauto2l.o deleted"
		sudo gcc -Wall -o "pxauto2l" "pxauto2l.c" -lmenu -lform -lpanel -lncurses -lrt -lpixtend -lwiringPi
		sudo chmod +x ./pxauto2l
		echo "makepxauto2l: pxauto2l compiled and built"
		echo "makepxauto2l: DONE!!"
		;;
	clean)
		echo "makepxauto2l: cleaning files"
		sudo rm -rf pxauto2l.o
		echo "./pxauto2l deleted"
		echo "makepxauto2l: DONE!!"
		;;
	*)
		echo "makepxauto2l: Available Options are \"go\" and \"clean\""
		;;
esac
