#!/bin/sh

case $1 in
	go)
		echo "makepixtendtool: started making pixtendtool"
		sudo rm -rf pixtendtool.o
		echo "./pixtendtool.o deleted"
		sudo gcc -Wall -o "pixtendtool" "pixtendtool.c" -lpixtend -lwiringPi
		sudo chmod +x ./pixtendtool
		echo "makepixtendtool: pixtendtool compiled and built"
		echo "makepixtendtool: DONE!!"
		;;
	clean)
		echo "makepixtendtool: cleaning files"
		sudo rm -rf pixtendtool.o
		echo "./pixtendtool.o deleted"
		echo "makepixtendtool: DONE!!"
		;;
	*)
		echo "makepixtendtool: Available Options are \"go\" and \"clean\""
		;;
esac
