#!/bin/sh

case $1 in
	go)
		echo "makepxauto: start making pxauto"
		sudo rm -rf pxauto.o
		echo "./pxauto.o deleted"
		sudo gcc -Wall -o "pxauto" "pxauto.c" -lmenu -lform -lpanel -lncurses -lrt -lpixtend -lwiringPi
		sudo chmod +x ./pxauto
		echo "makepxauto: pxauto compiled and built"
		echo "makepxauto: DONE!!"
		;;
	clean)
		echo "makepxauto: cleaning files"
		sudo rm -rf pxauto.o
		echo "./pxauto deleted"
		echo "makepxauto: DONE!!"
		;;
	*)
		echo "makepxauto: Available Options are \"go\" and \"clean\""
		;;
esac
